### ISSUE TITLE
Still got an error initializing Timestamp variables.

### ISSUE THREAD

**Issue by sermayoral** [enkama/hass-variables#104]
https://github.com/enkama/hass-variables/issues/102 still persists in v3.3.8.

The problem occurs when you fill out this window:

![imagen](https://github.com/enkama/hass-variables/assets/30116095/d6b3ed47-75cc-4e52-921c-4467f3c110ec)

Getting the following error and the variable unavailable:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 22:23:26 (1 occurrences)
Last logged: 22:23:26

Error adding entities for domain sensor with platform variable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 554, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.date_mto_descalcificacion_cafetera provides state '2023-11-23 09:00:00', which is missing timezone information

```

If you leave "initial value" empty, it works.

**Comment by Snuffy2** [comment]
Not sure if it's because you're in a different region so not sure if that may be the issue, but I cannot reproduce.  First, are you sure you're running v3.3.8?

Can you please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post the logs when creating a new timestamp variable to see if they show anything that may help.

<img width="527" alt="2023-11-24_18-27-05 908" src="https://github.com/enkama/hass-variables/assets/6526076/b9ef6a84-e7fc-4cc6-b5bc-d8bb70537518">
<img width="412" alt="2023-11-24_18-27-29 427" src="https://github.com/enkama/hass-variables/assets/6526076/f3b30767-0371-464e-b740-b4392b26d5c7">
<img width="590" alt="2023-11-24_18-27-48 943" src="https://github.com/enkama/hass-variables/assets/6526076/cad59663-430d-42f8-9088-cbe1809a77ef">

**Comment by sermayoral** [comment]
You are completely right. I wasn't running v3.3.8. I thought i was. Very strange. Sorry :-(

Setting a value creating a new timestamp sensor doesn't crash anymore :-). Although the date you enter is in UTC, and then it is converted to your time zone:

![imagen](https://github.com/enkama/hass-variables/assets/30116095/64866268-a8f6-4f5f-b0eb-1b6f0620b19b)

My timezone is GMT+1:

![imagen](https://github.com/enkama/hass-variables/assets/30116095/7aac6783-a22c-4f32-b081-b873ea4a6f51)

Also, updating a timestamp type sensor seems to have no effect

![imagen](https://github.com/enkama/hass-variables/assets/30116095/c7154fdb-65a1-4b9a-b2f1-a76066f0d9ad)

Last change and last update attributes change, but the state doesn't in:

![imagen](https://github.com/enkama/hass-variables/assets/30116095/490ac0c4-dc9a-4a1b-a1c1-24f51d796b1a)

Thanks

**Comment by Snuffy2** [comment]
I just noticed that I think you are trying to update the value of an existing variable using the Configuration page. In general, that won't work. You need to call one of the Variable Services to update (`variable.update_sensor`). When I update a timestamp Variable Sensor using `variable.update_sensor` it updates for me.

<img width="589" alt="2023-11-30_17-16-38 211" src="https://github.com/enkama/hass-variables/assets/6526076/84f3a40c-f0b2-498b-b5ad-16dcd763877c">

<img width="1094" alt="2023-11-30_17-16-50 976" src="https://github.com/enkama/hass-variables/assets/6526076/aaaccfcf-d6c3-419c-85b0-7166c1ba04e9">

<img width="589" alt="2023-11-30_17-17-08 722" src="https://github.com/enkama/hass-variables/assets/6526076/72d62205-c018-4d28-8364-badcd47611b6">

I'll still look to add a timezone selector when creating a new timestamp Variable Sensor but no eta on that.
