### ISSUE TITLE
Cannot create a timestamp variable

### ISSUE THREAD

**Issue by skipper-83** [enkama/hass-variables#110]
Hey there! Thanks for this great helper integration!

I might be doing something wrong, but I can't seem to be able to make a timestamp variable. I keep getting this error on config page 2:

<img width="571" alt="afbeelding" src="https://github.com/enkama/hass-variables/assets/85173659/bc729045-eca4-4ba9-9601-3821f1ba3dbf">

does it perhaps get a long data-type from the config script?

edit: in the screenshot it seems i did not enter a date: i did. If I do not, I get this error:

<img width="562" alt="afbeelding" src="https://github.com/enkama/hass-variables/assets/85173659/656fffc4-c774-4eee-8aa3-335901b4aa1c">

kind regards,
Albert van Andel

**Comment by Snuffy2** [comment]
Hmmmm.... I'm not able to reproduce this.

If I set a Date and Time it creates it just fine.
<img width="522" alt="2023-12-21_19-14-32 661" src="https://github.com/enkama/hass-variables/assets/6526076/cf6eb51c-4f85-4829-9729-e3cc418f076a">
<img width="415" alt="2023-12-21_19-14-48 747" src="https://github.com/enkama/hass-variables/assets/6526076/edf2f455-9b3d-48a1-88bb-25c7b162423b">

Additionally, if I leave the Date blank, it also creates it but with a State of Unknown.
<img width="522" alt="2023-12-21_19-24-58 226" src="https://github.com/enkama/hass-variables/assets/6526076/d0d831ab-f160-48fa-971c-9866e4769a11">
<img width="597" alt="2023-12-21_19-26-02 346" src="https://github.com/enkama/hass-variables/assets/6526076/32ff90cb-6224-4d6f-8f0e-350d053c8f83">

Anything in the HA logs?

**Comment by skipper-83** [comment]
That's a quick response! Nothing in the logs unfortunately. I do run HA in a Docker container on a Synology NAS, could that be of influence?

**Comment by Snuffy2** [comment]
No, I don't think it being run in a Docker on Synology would be the cause.

Are you manually typing in the Date or using the Date picker?
Can you show me a screenshot of Page 2 with the date and time filled in before you click submit?
I see your timezone offset is +0100. What country are you in (so I can try to reproduce)?
