### ISSUE TITLE
Set Location for sensors

### ISSUE THREAD

**Issue by DanfieldNet** [enkama/hass-variables#117]
Not exactly sure how to ask this, as I'm not sure what needs to be done to accommodate it, but I'd like to set a location for the sensors created by this integration; however, when attempting to do so, it indicates that there is no unique id.  So maybe that's what I need to request?  I don't know...

**Comment by Snuffy2** [comment]
The variables do get a unique id set behind the scenes. I'm not seeing this. Are you still having this problem?
