### ISSUE TITLE
Decimal precision

### ISSUE THREAD

**Issue by Sonusss** [enkama/hass-variables#119]
It would be nice to be able to specify displayed decimal precision

**Comment by Snuffy2** [comment]
You should be able to do that already for sensor variables with a number-type device class.
<img width="592" alt="2024-05-20_22-18-35 020" src="https://github.com/enkama/hass-variables/assets/6526076/aca6791d-76d7-45c8-b1e6-01217cc6877a">

**Comment by Sonusss** [comment]
Oups... Sorry I missed this
