### ISSUE TITLE
[Feature Request] Configure doesn't show the current content of the variable

### ISSUE THREAD

**Issue by davidolrik** [enkama/hass-variables#58]
I have created a variable `sensor.foo` and added a few attributes to it.
My variable has restore on restart = true and exclude from recorder = true.

Over time I have used the `variable.update_sensor` service to add more attribute data.

When I go to the integrations tab to edit the attributes, I'm shown the initial attributes and not the current contents of my variable.

Is this a bug or intentional behaviour?

**Comment by Snuffy2** [comment]
That is intentional behavior. 

If you have restore on restart = True, there really isn't any reason to change the Initial Values in the Integration Config. These are only used:
1. When the Variable is created
2. When restore on restart = False and Home Assistant is restarted

**Comment by davidolrik** [comment]
I do that too - it just seems less elegant, than the UI for the helpers.
And for my use case, the initial values I see in the integration UI makes no sense as I never want to go back to the beginning.

**Comment by marcelhoogantink** [comment]
Same here
