### ISSUE TITLE
Registering subattributes

### ISSUE THREAD

**Issue by sigalou** [enkama/hass-variables#94]
Hello everyone and congratulations for this integration.

I would like to use it to record the loads of my Wallbox in a sensor.
I have already done this via a Python script but it would be much simpler to do it with this integration.
Here is what I would like to get as a data result:

![image](https://github.com/Wibias/hass-variables/assets/26350534/9c0569c8-23fc-4002-a4b3-fd4bb2755544)

So I use an attribute which is "sessionscharge:" (charging sessions in English)

And each record contains 7 fields :
![image](https://github.com/Wibias/hass-variables/assets/26350534/b72284bc-85a2-4acb-b603-cd2f9dd4d80b)

I understood very well how the integration works when you want to add a record as an attribute and the "Merge" option is super practical, well done!
But if I want to add a subattribute (a load session in my example), it doesn't work.

![image](https://github.com/Wibias/hass-variables/assets/26350534/1637103e-180d-4608-bc9d-1f091c51914e)

Thus, if the attribute does not exist, it should be added with its subattributes (this works). And if the attribute exists, when we execute this Update Sensor Variable command, the sub-attribute (new charge) is added to the "sessionscharge:" attribute in my example.

Does this exist and work but I haven't been able to implement it? Or is this a feature that can be added? It would be particularly useful for many applications.

Thank you so much

**Comment by Snuffy2** [comment]
Try this...

Starting point:
<img width="596" alt="2023-10-26_21-45-05 694" src="https://github.com/Wibias/hass-variables/assets/6526076/7d495e4c-5afb-492e-bd63-64952fabaff8">

Service call:
<img width="1142" alt="2023-10-26_21-47-54 752" src="https://github.com/Wibias/hass-variables/assets/6526076/da80c19a-5b06-4770-a724-8bbd0cf494d6">

After Service call:
<img width="598" alt="2023-10-26_21-46-40 810" src="https://github.com/Wibias/hass-variables/assets/6526076/52aaf0a1-a948-4ca3-8cdd-bae114b5eca2">
