### ISSUE TITLE
[Feature Request] Multiple entities per entry

### ISSUE THREAD

**Issue by Timmiej93** [enkama/hass-variables#96]
The HA UI offers some nice ordering options for integrations, where things can be an entry, device and entity. It seems like currently we can only add entries to this integration, which all have a single entity. This makes ordering things difficult (not impossible, but you'd need to use prefixes or similar hacks). For example, in my case, have a few things I want to store related to my rain gauge that can't be attributes of one variable. It would be very nice if I was able to add another entity to the ZigbeeRainSensor entry as shown in the image below. AFAIK, the only option to add another variable currently is to have something like `ZigbeeRainSensor - main` and `ZigbeeRainSensor - secondary`.

Is it possible to add multiple entities to an entry? If not, is this something that might be added in the future?

![image](https://github.com/Wibias/hass-variables/assets/16491748/a9670cc1-ea98-47bf-97bf-94bb3098aed7)

**Comment by Snuffy2** [comment]
You are correct that, currently, each entity is a separate entry and that it is not setup to create devices with one or more entities per device.

Not sure that this is a change I'll get to anytime soon but I'm sure @Wibias would gladly review a PR by anyone else who was interested in implementing it.

**Comment by Snuffy2** [comment]
#138 will allow you to group multiple variables into a device

**Comment by enkama** [comment]
Closed by https://github.com/enkama/hass-variables/pull/138
